<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-07T13:29:59 IST" name="Default suite" finished-at="2023-05-07T13:30:24 IST" duration-ms="25587">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runnerClass.RunnerIO@16ec5519]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-05-07T13:29:59 IST" name="Default test" finished-at="2023-05-07T13:30:24 IST" duration-ms="25587">
      <class name="runnerClass.RunnerIO">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:runnerClass.RunnerIO@16ec5519]" started-at="2023-05-07T13:29:59 IST" name="setUpClass" finished-at="2023-05-07T13:30:00 IST" duration-ms="786" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runnerClass.RunnerIO@16ec5519]" started-at="2023-05-07T13:30:00 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-07T13:30:24 IST" duration-ms="24668" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login to VTiger appication with valid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Login to Vtiger Application]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefination.LoginTest.i_validate_for_home_page(LoginTest.java:50)
at âœ½.I validate for home page(file:///C:/Selenium%20Floder/Selenium-programs/Selenium%20Practice/BDD_FrameworkPractice/./src/test/java/FeatureFiles/Login.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:runnerClass.RunnerIO@16ec5519]" started-at="2023-05-07T13:30:24 IST" name="tearDownClass" finished-at="2023-05-07T13:30:24 IST" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runnerClass.RunnerIO -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
