<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="prasanth" failures="1" tests="1" name="runnerClass.RunnerIO" time="24.668" errors="0" timestamp="2023-05-07T13:30:25 IST" skipped="0">
  <testcase classname="runnerClass.RunnerIO" name="runScenario" time="24.668">
    <failure message="expected [vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefination.LoginTest.i_validate_for_home_page(LoginTest.java:50)
at âœ½.I validate for home page(file:///C:/Selenium%20Floder/Selenium-programs/Selenium%20Practice/BDD_FrameworkPractice/./src/test/java/FeatureFiles/Login.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runnerClass.RunnerIO -->
